### ISSUE TITLE
Running Ansible for the first time and auth problems

### ISSUE THREAD

**Issue by patrickwolf** [DonDebonair/statserver#4]
Hey, thanks for your package!
Just wanted to let you know that it took me a long time to figure out why the ansible-playbook command didn't work.

This is the end result which worked for me on Ubuntu:
ansible-playbook statserver.yml -i myinventory --ask-pass --user=MyUserName --sudo-user=root --ask-sudo-pass --sudo

ie 
--user is my user name
--sudo-user is root and NOT my user name

Just wanted to post that for other users.
Best,
Patrick

**Comment by DonDebonair** [comment]
Thanks for your comment, and sorry for not getting back to you sooner :)
I personally always run my playbooks against servers on which I have a user account with the same name as on my local machine. If that isn't the case, you should indeed set `--sudo-user`. Furthermore, I'd advise to use passwordless logins on all of your servers, and disable password-login capabilities asap. I have [had some problems](http://dandydev.net/blog/crashing-servers-and-riding-waves#.VL9_ii7F9Dc) with this in the past :)
